name: ROS2 CI Pipeline

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint (ament)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        linter: [cpplint, uncrustify, xmllint]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.7

      - name: Run linter
        uses: ros-tooling/action-ros-lint@v0.1
        with:
          linter: ${{ matrix.linter }}
          package-name: |
            sensor_reading

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
    
      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
    
      - name: Update apt
        run: sudo apt-get update
    
      - name: Run ROS2 CI
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
          package-name: sensor_reading
